FROM continuumio/miniconda3

WORKDIR /SMART - CORE

COPY ["SMART - CORE/", "."]

RUN conda install -c anaconda beautifulsoup4
RUN conda install numpy
RUN conda install scikit-learn
RUN conda install -c conda-forge filelock
RUN pip install summa
RUN conda install -c anaconda gensim
RUN pip install sentence-transformers
RUN pip install matplotlib
